### ISSUE TITLE
Preflight respons is not succesful

### ISSUE THREAD

**Issue by KangKai1982** [hassio-addons/addon-bitwarden#7]
There is a know issue:
got error message "Preflight respons is not succesful" when login with the safari extension.

and it is been fixed in the Bitwarden_rs release [2c2276c](https://github.com/dani-garcia/bitwarden_rs/commit/2c2276c5bb2fa3a1c8078b1d7ea6185bb769e4e9)

but this bug still represents in this add-on

Can you please update to the latest Bitwarden_rs release to fix it ?

Thanks.

**Comment by frenck** [comment]
The addon already run on the latest available version: 1.10.0

**Comment by JarydX** [comment]
Hi there,

On the new MacOS Catalina with bundled Safari Version 13.0.2, the browser addon tells us „Preflight response not successful“ when trying to login to my instance. 

The fix is not included in 1.10.0 (https://github.com/dani-garcia/bitwarden_rs/issues/628), but according to my home assistant this is the latest version available.
